version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg BITBUCKET_USERNAME=$GIT_USERNAME --build-arg BITBUCKET_PASSWORD=$GIT_PASSWORD ./docker-misc
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '{"Image":"%s:%s"}' $IMAGE_REPO_NAME $IMAGE_TAG > build.json
artifacts:
  files:
    - build.json
    - cfn/service.yml
    - cfn/environments/production.json
  discard-paths: yes
