Parameter:
  Cluster:
    Type: String
  DesiredCount:
    Type:String
  Image:
    Type:String
  Role:
    Type:String
  TargetGroupArm:
    Type:String

Resources:
  Services:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      Role: !Ref Role
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        -ContainerName: node
        -ContainerPort: 80
        -TargetGroupArn: !Ref TargetGroupArm

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Service
      ContainerDefinition:
        -Name: node
        -Image: !Ref Image
        -Memory: 512
        -PortMappings:
          -ContainerPort: 80
